import type { NextPage } from "next";
import Head from "next/head";
import MainSection from "../components/MainSection";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection />
    </div>
  );
};

export default Home;
